export const SIGN_UP = '/signup'
export const SIGN_IN = '/signin'
export const LANDING = '/'
export const PROFILE = '/profile'
export const PROJECTS = '/projects'
export const MY_PROJECTS = '/my_projects'
export const ACCOUNT = '/account'
export const PASSWORD_FORGET = '/password_forget'
